### ISSUE TITLE
Show single gallery, Images do not show up

### ISSUE THREAD

**Issue by pixeldesignstudio** [ChristianGiupponi/PyroCMS-Galleries-pro#5]
{{ pro_galleries_images }} shows "array"
{{ pro_galleries_images:id }} shows nothing
{{ pro_galleries_images:img }} shows only one image 

I also tried: 

{{ pro_galleries:show_gallery slug="the-gallery" }}
    {{ pro_galleries_name }}
    <img src="{{ url:site }}files/thumb/{{ pro_galleries_images:img }}">
{{ /pro_galleries:show_gallery }}

**Comment by ChristianGiupponi** [comment]
Sorry for the delay, to use the width you should use the image ID, something like:

````
{{ pro_galleries_images }}
    <img src="{{ url:site }}files/{{ image }}/150>
{{ /pro_galleries_images }}
```

**Comment by pixeldesignstudio** [comment]
I did not see the ID in your example.
But it does not work, sorry.
<img src="{{ image }}" class="thumb">
neither
<img src="{{ image:id }}" class="thumb">

{{ image }} returns the full URL to the large image.

**Comment by pixeldesignstudio** [comment]
{{ pro_galleries_images }}
    <img src="{{ url:site }}files/{{ image }}/150>
{{ /pro_galleries_images }}

Where is the ID in your example?

**Comment by ChristianGiupponi** [comment]
{{ image }} should be the ID

**Comment by pixeldesignstudio** [comment]
ok now I understand: `<img src="{{ url:site }}files/thumb/{{ id }}/235/160/fit" class="thumb">`

Because the cover looks like: `<img src="{{ url:site }}files/thumb/{{ pro_galleries_cover:id }}/270/195" class="thumb">`

Thanks
