### ISSUE TITLE
Related field is shown twice

### ISSUE THREAD

**Issue by pixeldesignstudio** [ChristianGiupponi/PyroCMS-Galleries-pro#6]
By creating a new field and choosing "relationship field" I can choose "pro_galleries_categores".
![image](https://cloud.githubusercontent.com/assets/9533914/5711462/0e794976-9aab-11e4-88d8-97a6a6ef1756.png)
But after saving and editing the field again, the field is shown twice:
![image](https://cloud.githubusercontent.com/assets/9533914/5711472/22d50022-9aab-11e4-9045-50dc82e066f6.png)

So {{ page:gallery }} shows "Array" and {{ page:gallery:value }} or {{ page:gallery:key }} does not work.

**Comment by pixeldesignstudio** [comment]
I need this urgent, the project is on hold at the moment. 
Thank you

**Comment by ChristianGiupponi** [comment]
Hi pixeldesignstudio,
how are you using the module? This is built on Streams API and has its own Backend GUI, are you trying to use it via Streams Plugin?

**Comment by pixeldesignstudio** [comment]
Hi,

I created a field in the pagetype "default" as shown in the screenshots.
The stream plugin is not installed on this project.

Pyro Version: 2.2.5

2015-01-16 9:21 GMT+01:00 Christian Giupponi <notifications@github.com>:

> Hi pixeldesignstudio,
> how are you using the module? This is built on Streams API and has its own
> Backend GUI, are you trying to use it via Streams Plugin?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChristianGiupponi/PyroCMS-Galleries-pro/issues/6#issuecomment-70221572>
> .
>



-- 


*Wichtiger Hinweis:* Diese E-Mail und etwaige Anlagen können Betriebs- oder
Geschäftsgeheimnisse, oder sonstige vertrauliche Informationen enthalten.
Sollten Sie diese E-Mail irrtümlich erhalten haben, ist Ihnen der Status
dieser E-Mail bekannt. Bitte benachrichtigen Sie uns in diesem Fall sofort
durch Antwort-Mail und löschen diese E-Mail nebst etwaigen Anlagen von
Ihrem System. Ebenso dürfen Sie diese E-Mail oder ihre Anlagen nicht
kopieren oder an Dritte weitergeben. Vielen Dank!

*Important Note:* This e-mail including any attachment is confidential and
may contain trade secrets or other confidential information. If you have
received it in error, you are aware of its status. Please notify us
immediately by reply e-mail and then delete this e-mail and any attachment
from your system. If you are not the intended recipient, you are not
allowed to copy this e-mail or any attachment or disclose the content to
any other person. Thank you for your cooperation.

**Comment by ChristianGiupponi** [comment]
You do not need to add a field type in the page.  
Once you created your page layout add in your html code:

~~~
{{ pro_galleries:show_gallery slug="your_gallery_slug" }}

    {{ pro_galleries_name }}

    {{ pro_galleries_images }}
        {{ image }}
    {{ /pro_galleries_images }}

{{ /pro_galleries:show_gallery }}
~~~

and it will display the gallery name and the images.

**Comment by pixeldesignstudio** [comment]
For my purpose I need it:

              {{ if { page:gallery_category } != "" }}
              <ul class="portfolio_items">
              {{ pro_galleries:get_galleries_by_category slug="{{
page:gallery_category }}" }}
...
                        <img src="{{ url:site }}files/thumb/{{
pro_galleries_cover:id }}/280/195" class="thumb">
...
              {{ /pro_galleries:get_galleries_by_category }}
              </ul>
              {{ endif }}

Explained: If a gallery is choosen display it, if not don't show it.


But the relation-field "page:gallery_category" says "array" instead of the
gallery-category choosen in the dropdown field.




2015-01-17 12:15 GMT+01:00 Christian Giupponi <notifications@github.com>:

> You do not need to add a field type in the page.
>
> Once you created your page layout add in your html code:
>
> {{ pro_galleries:show_gallery slug="your_gallery_slug" }}
>
>     {{ pro_galleries_name }}
>
>     {{ pro_galleries_images }}
>         {{ image }}
>     {{ /pro_galleries_images }}
>
> {{ /pro_galleries:show_gallery }}
>
> and it will display the gallery name and the images.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChristianGiupponi/PyroCMS-Galleries-pro/issues/6#issuecomment-70363245>
> .
>



-- 


*Wichtiger Hinweis:* Diese E-Mail und etwaige Anlagen können Betriebs- oder
Geschäftsgeheimnisse, oder sonstige vertrauliche Informationen enthalten.
Sollten Sie diese E-Mail irrtümlich erhalten haben, ist Ihnen der Status
dieser E-Mail bekannt. Bitte benachrichtigen Sie uns in diesem Fall sofort
durch Antwort-Mail und löschen diese E-Mail nebst etwaigen Anlagen von
Ihrem System. Ebenso dürfen Sie diese E-Mail oder ihre Anlagen nicht
kopieren oder an Dritte weitergeben. Vielen Dank!

*Important Note:* This e-mail including any attachment is confidential and
may contain trade secrets or other confidential information. If you have
received it in error, you are aware of its status. Please notify us
immediately by reply e-mail and then delete this e-mail and any attachment
from your system. If you are not the intended recipient, you are not
allowed to copy this e-mail or any attachment or disclose the content to
any other person. Thank you for your cooperation.

**Comment by ChristianGiupponi** [comment]
Ok, so that's not a issue related to the module but the page plugin that display data.  
Did you tried to post it in the forum?

I will build a demo to check this out later

**Comment by pixeldesignstudio** [comment]
Thank you, sorry I thought it might be related to the module/plugin.

I will post this in the forum.

2015-01-19 17:13 GMT+01:00 Christian Giupponi <notifications@github.com>:

> Ok, so that's not a issue related to the module but the page plugin that
> display data.
>
> Did you tried to post it in the forum?
>
> I will build a demo to check this out later
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChristianGiupponi/PyroCMS-Galleries-pro/issues/6#issuecomment-70518966>
> .
>



-- 


*Wichtiger Hinweis:* Diese E-Mail und etwaige Anlagen können Betriebs- oder
Geschäftsgeheimnisse, oder sonstige vertrauliche Informationen enthalten.
Sollten Sie diese E-Mail irrtümlich erhalten haben, ist Ihnen der Status
dieser E-Mail bekannt. Bitte benachrichtigen Sie uns in diesem Fall sofort
durch Antwort-Mail und löschen diese E-Mail nebst etwaigen Anlagen von
Ihrem System. Ebenso dürfen Sie diese E-Mail oder ihre Anlagen nicht
kopieren oder an Dritte weitergeben. Vielen Dank!

*Important Note:* This e-mail including any attachment is confidential and
may contain trade secrets or other confidential information. If you have
received it in error, you are aware of its status. Please notify us
immediately by reply e-mail and then delete this e-mail and any attachment
from your system. If you are not the intended recipient, you are not
allowed to copy this e-mail or any attachment or disclose the content to
any other person. Thank you for your cooperation.

**Comment by pixeldesignstudio** [comment]
I got it working, by printing out the array I found the write code:

{{ pro_galleries:get_galleries_by_category slug="{{
page:gallery_category:pro_galleries_categories_slug }}" }}



2015-01-19 17:27 GMT+01:00 PIXEL Design Studio <info@pixel-design-studio.de>
:

> Thank you, sorry I thought it might be related to the module/plugin.
>
> I will post this in the forum.
>
> 2015-01-19 17:13 GMT+01:00 Christian Giupponi <notifications@github.com>:
>
>> Ok, so that's not a issue related to the module but the page plugin that
>> display data.
>>
>> Did you tried to post it in the forum?
>>
>> I will build a demo to check this out later
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ChristianGiupponi/PyroCMS-Galleries-pro/issues/6#issuecomment-70518966>
>> .
>>
>
>
>
> --
>
>
> *Wichtiger Hinweis:* Diese E-Mail und etwaige Anlagen können Betriebs-
> oder Geschäftsgeheimnisse, oder sonstige vertrauliche Informationen
> enthalten. Sollten Sie diese E-Mail irrtümlich erhalten haben, ist Ihnen
> der Status dieser E-Mail bekannt. Bitte benachrichtigen Sie uns in diesem
> Fall sofort durch Antwort-Mail und löschen diese E-Mail nebst etwaigen
> Anlagen von Ihrem System. Ebenso dürfen Sie diese E-Mail oder ihre Anlagen
> nicht kopieren oder an Dritte weitergeben. Vielen Dank!
>
> *Important Note:* This e-mail including any attachment is confidential
> and may contain trade secrets or other confidential information. If you
> have received it in error, you are aware of its status. Please notify us
> immediately by reply e-mail and then delete this e-mail and any attachment
> from your system. If you are not the intended recipient, you are not
> allowed to copy this e-mail or any attachment or disclose the content to
> any other person. Thank you for your cooperation.
>



-- 


*Wichtiger Hinweis:* Diese E-Mail und etwaige Anlagen können Betriebs- oder
Geschäftsgeheimnisse, oder sonstige vertrauliche Informationen enthalten.
Sollten Sie diese E-Mail irrtümlich erhalten haben, ist Ihnen der Status
dieser E-Mail bekannt. Bitte benachrichtigen Sie uns in diesem Fall sofort
durch Antwort-Mail und löschen diese E-Mail nebst etwaigen Anlagen von
Ihrem System. Ebenso dürfen Sie diese E-Mail oder ihre Anlagen nicht
kopieren oder an Dritte weitergeben. Vielen Dank!

*Important Note:* This e-mail including any attachment is confidential and
may contain trade secrets or other confidential information. If you have
received it in error, you are aware of its status. Please notify us
immediately by reply e-mail and then delete this e-mail and any attachment
from your system. If you are not the intended recipient, you are not
allowed to copy this e-mail or any attachment or disclose the content to
any other person. Thank you for your cooperation.

**Comment by ChristianGiupponi** [comment]
Great, could you please tell how you printed the array? So if someone else need this, we have a solution

**Comment by pixeldesignstudio** [comment]
Simple PHP:

<?php print_r($this); ?>

Then search for the field name, in my case "gallery_category"

2015-01-19 18:00 GMT+01:00 Christian Giupponi <notifications@github.com>:

> Great, could you please tell how you printed the array? So if someone else
> need this, we have a solution
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChristianGiupponi/PyroCMS-Galleries-pro/issues/6#issuecomment-70526600>
> .
>



-- 


*Wichtiger Hinweis:* Diese E-Mail und etwaige Anlagen können Betriebs- oder
Geschäftsgeheimnisse, oder sonstige vertrauliche Informationen enthalten.
Sollten Sie diese E-Mail irrtümlich erhalten haben, ist Ihnen der Status
dieser E-Mail bekannt. Bitte benachrichtigen Sie uns in diesem Fall sofort
durch Antwort-Mail und löschen diese E-Mail nebst etwaigen Anlagen von
Ihrem System. Ebenso dürfen Sie diese E-Mail oder ihre Anlagen nicht
kopieren oder an Dritte weitergeben. Vielen Dank!

*Important Note:* This e-mail including any attachment is confidential and
may contain trade secrets or other confidential information. If you have
received it in error, you are aware of its status. Please notify us
immediately by reply e-mail and then delete this e-mail and any attachment
from your system. If you are not the intended recipient, you are not
allowed to copy this e-mail or any attachment or disclose the content to
any other person. Thank you for your cooperation.
